# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: research
    weight: 10
  - name: Multiomics Integration
    parent: Research         # Matches the 'identifier' above to become a child
    url: /research/multiomics-integration/ # Links to the AI frameworks research page
    weight: 1   
  - name: Causal Inference
    parent: Research         # Matches the 'identifier' above to become a child
    url: /research/causal-inference/ # Links to the single cell research page
    weight: 2   
  - name: Single-cell Genomics
    parent: Research         # Matches the 'identifier' above to become a child
    url: /research/single-cell-genomics/ 
    weight: 3   
  - name: Pharmacogenomics
    parent: Research         # Matches the 'identifier' above to become a child
    url: /research/pharmacogenomics/ 
    weight: 4 
  - name: Genomic Foundation Models
    parent: Research         # Matches the 'identifier' above to become a child
    url: /research/genomic-foundation-models/ 
    weight: 5
  - name: Test
    parent: Research         # Matches the 'identifier' above to become a child
    url: /research/test/ 
    weight: 5
  - name: People
    url: people
    weight: 20
  - name: Publications
    url: publication
    weight: 30
  - name: News
    url: news
    weight: 40
  - name: Opening
    url: opening
    weight: 50
  - name: Software
    url: software
    weight: 50
  - name: Contact
    url: contact
    weight: 60
