[build]
  command = "hugo --minify --cleanDestinationDir --ignoreCache -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.124.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --minify --cleanDestinationDir --ignoreCache --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --minify --cleanDestinationDir --ignoreCache -b $DEPLOY_PRIME_URL"
